In [1]:
using DSP: conv

In [2]:
test_str = readlines("day4_test.txt")

10-element Vector{String}:
 "..@@.@@@@."
 "@@@.@.@.@@"
 "@@@@@.@.@@"
 "@.@@@@..@."
 "@@.@@@@.@@"
 ".@@@@@@@.@"
 ".@.@.@.@@@"
 "@.@@@.@@@@"
 ".@@@@@@@@."
 "@.@.@@@.@."

In [5]:
function make_2dmat(lines::AbstractVector{<:AbstractString})
    map_fn = x -> vcat([c == '@' for c in x])
    mat = stack(map_fn.(lines)) .* 1
end

make_2dmat (generic function with 1 method)

In [6]:
m = make_2dmat(test_str)

10×10 Matrix{Int64}:
 0  1  1  1  1  0  0  1  0  1
 0  1  1  0  1  1  1  0  1  0
 1  1  1  1  0  1  0  1  1  1
 1  0  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  0  1  1  1
 1  0  0  1  1  1  1  0  1  1
 1  1  1  0  1  1  0  1  1  1
 1  0  0  0  0  1  1  1  1  0
 1  1  1  1  1  0  1  1  1  1
 0  1  1  0  1  1  1  1  0  0

In [7]:
function moore_kernel(r::Int)
    d = 2*r+1
    center = r+1
    k = ones(Int, (d,d))
    k[center, center] = 0
    return k
end

moore_kernel (generic function with 1 method)

In [8]:
k = moore_kernel(1)

3×3 Matrix{Int64}:
 1  1  1
 1  0  1
 1  1  1

In [9]:
function get_accessible(inventory::AbstractMatrix; limit::Int=4)
    k = moore_kernel(1)
    neighbors = conv(inventory, k, algorithm = :direct)[2:end-1,2:end-1]
    return neighbors .< limit .* inventory
end

get_accessible (generic function with 1 method)

In [10]:
get_accessible(m)

10×10 BitMatrix:
 0  1  0  0  1  0  0  1  0  1
 0  0  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  0  0  1
 1  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  0  0  0
 1  0  1  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  0  0  1
 0  0  0  0  1  0  0  0  0  0

In [11]:
get_accessible(m) |> sum

13

In [22]:
function get_paper(inventory::AbstractMatrix, total::Int)
    stock = get_accessible(inventory)
    if sum(stock) == 0
        return total
    else
        new_inventory = inventory .- stock
        total += sum(stock)
        return get_paper(new_inventory, total)
    end
end

get_paper (generic function with 1 method)

In [23]:
s = get_paper(m, 0)

43

In [25]:
bigm = make_2dmat(readlines("day4_input.txt"));

In [27]:
get_accessible(bigm) |> sum

1424

In [29]:
get_paper(bigm, 0)

8727

In [13]:
m2, t2 = get_paper(m, 0)

([0 0 … 0 0; 0 1 … 1 0; … ; 0 1 … 1 0; 0 1 … 0 0], 13)

In [14]:
m2

10×10 Matrix{Int64}:
 0  0  1  1  0  0  0  0  0  0
 0  1  1  0  1  1  1  0  1  0
 0  1  1  1  0  1  0  1  1  0
 0  0  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  0  1  1  1
 0  0  0  1  1  1  1  0  1  1
 0  1  0  0  1  1  0  1  1  1
 1  0  0  0  0  1  1  1  1  0
 0  1  1  1  1  0  1  1  1  0
 0  1  1  0  0  1  1  1  0  0

In [15]:
conv(m2, k, algorithm = :direct)[2:end-1,2:end-1] .< 4 .* m2

10×10 BitMatrix:
 0  0  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  1  0  1  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  0  0  0
 0  0  0  1  1  0  0  0  0  0
 0  1  0  0  0  1  0  0  0  0

In [16]:
get_accessible(m2)

10×10 BitMatrix:
 0  0  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  1  0  1  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  0  0  0
 0  0  0  1  1  0  0  0  0  0
 0  1  0  0  0  1  0  0  0  0

In [17]:
m3, t3 = get_paper(m2, 13)

([0 0 … 0 0; 0 1 … 0 0; … ; 0 1 … 1 0; 0 0 … 0 0], 25)

In [21]:
get_accessible(m3) |> sum

7