In [1]:
using DelimitedFiles

In [136]:
mvs = stack(readlines("day6_test.txt")[1:3])

15×3 Matrix{Char}:
 '1'  ' '  ' '
 '2'  '4'  ' '
 '3'  '5'  '6'
 ' '  ' '  ' '
 '3'  '6'  '9'
 '2'  '4'  '8'
 '8'  ' '  ' '
 ' '  ' '  ' '
 ' '  '3'  '2'
 '5'  '8'  '1'
 '1'  '7'  '5'
 ' '  ' '  ' '
 '6'  '2'  '3'
 '4'  '3'  '1'
 ' '  ' '  '4'

In [141]:
vals = [filter(x -> x != ' ', c) for c in eachslice(mvs, dims=1)]

15-element Vector{Vector{Char}}:
 ['1']
 ['2', '4']
 ['3', '5', '6']
 []
 ['3', '6', '9']
 ['2', '4', '8']
 ['8']
 []
 ['3', '2']
 ['5', '8', '1']
 ['1', '7', '5']
 []
 ['6', '2', '3']
 ['4', '3', '1']
 ['4']

In [145]:
nums = [sum(parse.(Int, x) .* 10 .^ ((length(x)-1):-1:0)) for x in vals]

15-element Vector{Int64}:
   1
  24
 356
   0
 369
 248
   8
   0
  32
 581
 175
   0
 623
 431
   4

In [151]:
reshape(filter(x -> x != 0, nums), (3,4))

3×4 Matrix{Int64}:
   1  369   32  623
  24  248  581  431
 356    8  175    4

In [152]:
function read_input(filename::String)
    vals = readdlm(filename)
    numbers = Int.(vals[1:end-1, 1:end-1])
    ops = vals[end, 1:end-1]
    return numbers, ops
end

read_input (generic function with 1 method)

In [ ]:
function read_input(filename::String)
    vals_mat = stack(readdlm(filename)[1:end-1])
    n_rows = size(vals_mat,2)
    vals = [filter(x -> x != ' ', c) for c in eachslice(vals_mat, dims=1)]
    ops = vals[end, 1:end-1]
    return numbers, ops
end

In [176]:
function read_cephalopod(filename::String)
    vals_mat = stack(readlines(filename)[1:end-1])
    n_rows = size(vals_mat,2)
    vals = [filter(x -> x != ' ', c) for c in eachslice(vals_mat, dims=1)]
    #return vals
    nums = [sum(parse.(Int, x) .* 10 .^ ((length(x)-1):-1:0)) for x in vals]
    #nums = reshape(filter(x -> x != 0, nums), (n_rows, :))
    return nums
end

read_cephalopod (generic function with 1 method)

In [169]:
nums, ops = read_input("day6_test.txt")

([123 328 51 64; 45 64 387 23; 6 98 215 314], Any["*", "+", "*", "+"])

In [174]:
split

split (generic function with 2 methods)

In [177]:
nums2 = read_cephalopod("day6_test.txt")

16-element Vector{Int64}:
   1
  24
 356
   0
 369
 248
   8
   0
  32
 581
 175
   0
 623
 431
   4
   0

In [196]:
idx = vcat([0,], findall(nums2 .== 0))

1001-element Vector{Int64}:
    0
    3
    6
   11
   15
   18
   21
   24
   29
   33
   36
   40
   43
    ⋮
 3748
 3752
 3756
 3759
 3764
 3769
 3773
 3777
 3781
 3785
 3788
 3791

In [199]:
rngs = [(idx[i]+1):(idx[i+1]-1) for i in 1:length(idx)-1]

1000-element Vector{UnitRange{Int64}}:
 1:2
 4:5
 7:10
 12:14
 16:17
 19:20
 22:23
 25:28
 30:32
 34:35
 37:39
 41:42
 44:46
 ⋮
 3746:3747
 3749:3751
 3753:3755
 3757:3758
 3760:3763
 3765:3768
 3770:3772
 3774:3776
 3778:3780
 3782:3784
 3786:3787
 3789:3790

In [204]:
cnums = [nums2[rng] for rng in rngs]

1000-element Vector{Vector{Int64}}:
 [9631, 88]
 [8368, 1236]
 [56, 181, 9197, 6418]
 [9141, 1323, 675]
 [1, 8429]
 [6398, 98]
 [2321, 5848]
 [953, 952, 388, 1898]
 [3484, 899, 3]
 [3589, 9676]
 [767, 5231, 3826]
 [4, 9677]
 [49, 3141, 5682]
 ⋮
 [2821, 87]
 [9365, 6675, 615]
 [716, 7155, 9356]
 [1, 3928]
 [55, 191, 7744, 4418]
 [9734, 9545, 521, 87]
 [2, 81, 6868]
 [447, 8445, 6853]
 [149, 2155, 7919]
 [246, 1441, 8168]
 [9337, 915]
 [43, 5328]

In [191]:
nums2 = read_cephalopod("day6_input.txt")

3791-element Vector{Int64}:
 9631
   88
    0
 8368
 1236
    0
   56
  181
 9197
 6418
    0
 9141
 1323
    ⋮
 7919
    0
  246
 1441
 8168
    0
 9337
  915
    0
   43
 5328
    0

In [154]:
nums

3×4 Matrix{Int64}:
 123  328   51   64
  45   64  387   23
   6   98  215  314

In [19]:
function do_column(numbers::AbstractArray, op::AbstractString)
    if op == "*"
        return reduce(*, numbers)
    elseif op == "+"
        return reduce(+, numbers)
    elseif op == "/"
        return reduce(/, numbers)
    elseif op == "-"
        return reduce(-, numbers)
    else
        error("Unrecognized cephalopod math op!!")
    end
end

do_column (generic function with 2 methods)

In [21]:
do_column(nums[:,1], ops[1])

33210

In [122]:
nums[:,2]

3-element Vector{Int64}:
 328
  64
  98

In [112]:
function cephalopod_transpose(numbers::AbstractArray{<:Real})
    powers = 0:size(numbers,1)-1
    power_split = [mod.(div.(numbers, 10^p), 10) for p in powers]
    power_split = filter.(x -> x != 0, power_split)
    numbers = [sum(p .* 10 .^ ((length(p)-1):-1:0)) for p in power_split]
    return numbers
end
    

cephalopod_transpose (generic function with 2 methods)

In [113]:
c = 

3-element Vector{Int64}:
 123
  45
   6

In [114]:
a = cephalopod_transpose(c)

3-element Vector{Int64}:
 356
  24
   1

In [92]:
function do_homework(numbers::AbstractMatrix{<:Real}, ops::AbstractVector)
    return sum([do_column(numbers[:,i], ops[i]) for i in 1:length(ops)])
end

do_homework (generic function with 1 method)

In [116]:
function do_cephalopod_homework(numbers::AbstractMatrix{<:Real}, ops::AbstractVector)
    return sum([do_column(cephalopod_transpose(numbers[:,i]), ops[i]) for i in 1:length(ops)])
end

do_cephalopod_homework (generic function with 1 method)

In [120]:
[cephalopod_transpose(nums[:,i]) for i in 1:4]

4-element Vector{Vector{Int64}}:
 [356, 24, 1]
 [848, 269, 3]
 [175, 581, 32]
 [434, 621, 3]

In [26]:
do_homework(nums, ops)

4277556

In [161]:
do_homework(nums2, ops)

3263827

In [202]:
nums, ops = read_input("day6_input.txt")

([9 81 … 99 45; 6 32 … 31 33; 38 63 … 35 2; 18 86 … 7 8], Any["+", "*", "+", "*", "*", "*", "+", "+", "*", "*"  …  "*", "+", "+", "+", "*", "*", "*", "*", "+", "*"])

In [164]:
nums2 = read_cephalopod("day6_input.txt")

LoadError: DimensionMismatch: array size 2791 must be divisible by the product of the new dimensions (4, Colon())

In [163]:
do_homework(nums, ops)

5782351442566

In [203]:
ops

1000-element Vector{Any}:
 "+"
 "*"
 "+"
 "*"
 "*"
 "*"
 "+"
 "+"
 "*"
 "*"
 "*"
 "*"
 "*"
 ⋮
 "+"
 "*"
 "*"
 "+"
 "+"
 "+"
 "*"
 "*"
 "*"
 "*"
 "+"
 "*"

In [206]:
[do_column(cnums[i], ops[i]) for i in 1:length(ops)] |> sum

10194584711842